### ISSUE TITLE
Migrate OracleLinux7.9/8.x image to Aliyun

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/role_os#14]
Requirement 

1. Can use password and pairkey when create VM
2. Can automatic mount all the default system disk when create VM
3. Can reset password on Cloud console
4. Can resize system disk on Cloud console
5. remove waagent and waagent init
6. Reset Time Zone / UTC time

refer

API:https://help.aliyun.com/document_detail/25542.html
doc:https://help.aliyun.com/document_detail/25464.html

**Comment by chendelin1982** [comment]
System disk can't auto increase
suggest use `growpart `
refer to: https://blog.csdn.net/just_a_litte_body/article/details/109991898

**Comment by qiaofeng1227** [comment]
btrfs disk auto increase
```
btrfs filesystem resize max /data
btrfs filesystem resize max /
```

**Comment by qiaofeng1227** [comment]
If you want to auto increase into /, like this:
```
btrfs filesystem resize max /
```

**Comment by qiaofeng1227** [comment]
API:https://help.aliyun.com/document_detail/25542.html
doc:https://help.aliyun.com/document_detail/25464.html

**Comment by qiaofeng1227** [comment]
aliyun ecs ImportImage --RegionId cn-hongkong\
 --ImageName OracleLinux8.4test\
 --Architecture x86_64\
 --OSType linux\
 --DiskDeviceMapping.n.DiskImageSize 40\
 --DiskDeviceMapping.n.OSSBucket websoft9xg\
 --DiskDeviceMapping.n.OSSObject OracleLinux8.4.vhd

**Comment by chendelin1982** [comment]
LVM resize solution confirmed, refer to: https://support.websoft9.com/docs/linux/zh/admin-file.html#lvm
We need a automatic script to like this: [1](https://github.com/EugenMayer/parted-auto-resize), [2](https://github.com/ziozzang/automatic-lvm-expand/blob/master/expander.sh), it need to test

The suitable solution is that we should set the cloud.cfg
```
timezone: "Asia/Shanghai" 

growpart:
  mode: auto
  devices: [/dev/vda2]
  ignore_growroot_disabled: false

runcmd:
  - [pvresize,/dev/vda2]
  - [lvextend,-l,+100%FREE,/dev/rootvg/rootlv]
  - [xfs_growfs,/dev/rootvg/rootlv]
```
and we need to run `cloud-init clean` before download VHD
